language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - gradlew build --scan -s
deploy:
  provider: heroku
  api_key:
    secure:
  app:
    master: ChooseLang
    dev: ChooseLang (v1.2)