package ru.project.chooselang.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import javax.persistence.*;
import java.util.Collection;
import java.util.Set;

/**
 * User representation class
 * @author skwardlow
 * @version 1.0
 * @see UserDetails
 * @see Table
 * @see NoArgsConstructor
 * @see Entity
 */

@Getter
@Setter
@Entity
@Table(name = "usr")
@NoArgsConstructor
public class User implements UserDetails {

    /**
     * An id field for DB identification, automatically generated by db
     *
     * @see Id
     * @see GeneratedValue
     */

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Integer id;

    /**
     * User first name field
     */

    private String firstName;

    /**
     * User last name field
     */


    private String lastName;

    /**
     * User email field
     */

    private String email;

    /**
     * User username field for authentication
     */

    protected String username;

    /**
     * User password field for authentication
     */

    protected String password;

    /**
     * User account activity field
     */

    private boolean active;

    /**
     * User iconUrl field
     */

    private String iconUrl;

    /**
     * User book field for bind a collection of books to a user
     */

    @ManyToMany(cascade = CascadeType.ALL)
    Set<Book> books;

    /**
     * User role field for using in authorities in Spring security
     * creates and wires with User_role field.
     * user identifies by user_id field in table
     *
     * @see CollectionTable
     * @see Role
     * @see Enumerated
     */

    @ElementCollection(targetClass = Role.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "user_role",joinColumns = @JoinColumn(name = "user_id"))
    @Enumerated(EnumType.STRING)
    private Set<Role> roles;

    /**
     * Constructor for User object by:
     * @param firstName
     * @param lastName
     * @param email
     * @param username
     * @param password
     */

    public User(String firstName, String lastName, String email, String username, String password){
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.username = username;
        this.password = password;
    }

    /**
     * An default generated by UserDetails method, required by Spring security account management
     * @return Collection of Current user authorities
     */

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return getRoles();
    }

    /**
     * An default generated by UserDetails method, required by Spring security account management
     * @return boolean with account  IsNonExpired answer
     */

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * An default generated by UserDetails method, required by Spring security account management
     * @return boolean with account isNonLocked answer
     */

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * An default generated by UserDetails method, required by Spring security account management
     * @return boolean with account IsCredentialsNonExpired answer
     */

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * An default generated by UserDetails method, required by Spring security account management
     * @return boolean result switches account status to enabled
     */

    @Override
    public boolean isEnabled() {
        return true;
    }

    /**
     *
     * @return string object User
     */

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", active=" + active +
                ", iconUrl='" + iconUrl + '\'' +
                ", roles=" + roles +
                '}';
    }
}
